apiVersion: v2
name: pagopa-wisp-converter-technical-support
description: A service that permits to handle converted WISP requests for technical support
type: application
version: 0.45.0
appVersion: 0.3.2-4-feat-migrate-report-generator
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: cron
